server:
  port: 8085

spring:
  application:
    name: identity-service
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:microservice-realm}
  client-id: ${KEYCLOAK_CLIENT_ID:fiinx-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret} # Senior Note: Use K8s Secret or Env Var in Production
  admin:
    username: ${KEYCLOAK_ADMIN_USER:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    client-id: admin-cli

app:
  kafka:
    topics:
      user-created: user-events

# BEST PRACTICE: Observability
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

