spring:
  application:
    name: review-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/review_db
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: validate
  
  flyway:
    enabled: true
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fiinx

server:
  port: 8086

logging:
  level:
    com.fiinx.review: DEBUG
